{% set version = "1.1.6" %}

package:
  name: secapr
  version: {{ version }}

source:
  fn: secapr_{{ version }}.tar.gz
  url: https://github.com/AntonelliLab/seqcap_processor/archive/v{{ version }}.tar.gz
  sha256: 5c14c5d6d2de83ab49671043c4bca07d5dfce11909eef46f9ba7f61f589e4132

build:
  skip: True  # [not py27]
  number: 0
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - secapr = secapr.__main__:main

requirements:
  build:
    - python
    - setuptools
    - biopython
    - pandas

  run:
    - python
    - biopython
    - emboss
    - bcftools
    - samtools
    - picard
    - seqtk
    - bwa
    - lastz
    - mafft
    - muscle
    - trimmomatic
    - trinity =2.0.6
    - abyss
    - fastqc
    - seqtk
    - pandas
    - numpy 
    - cogent
    - java-jdk =7.0.91
    - r =3.4.3
    
test:
  imports:
    - secapr
  commands:
    - secapr --version

about:
  home: 'https://github.com/AntonelliLab/seqcap_processor'
  license: MIT
  license_file: LICENSE
  summary: 'Process sequence-capture FASTQ files into alignments for phylogenetic analyses. Integrates allele phasing, producing haplotype alignments.'
