{% set version = "1.1.13" %}

package:
  name: secapr
  version: {{ version }}

source:
  url: https://github.com/AntonelliLab/seqcap_processor/archive/v{{ version }}.tar.gz
  sha256: d4d90767c5ca1ba28906685b456f1b726b0386b84f4938c633f7ffeff8e6c08e

build:
  skip: True  # [not py27] 
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - secapr = secapr.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - biopython
    - pandas
    - r-base

  run:
    - python
    - biopython
    - emboss
    - bcftools ==1.8
    - samtools ==0.1.19
    - picard
    - seqtk >=1.0.82,<=1.2
    - bwa >=0.7
    - lastz
    - mafft >=7.2
    - muscle
    - trimmomatic >=0.3
    - abyss
    - trinity <=2.3.2
    - fastqc
    - pandas
    - numpy
    - cogent
    - r-base
    - r-tidyverse

test:
  imports:
    - secapr
  commands:
    - secapr --version

about:
  home: 'https://github.com/AntonelliLab/seqcap_processor'
  license: MIT
  license_file: LICENSE
  summary: 'Process sequence-capture FASTQ files into alignments for phylogenetic analyses. Integrates allele phasing, producing haplotype alignments.'
