{% set version = "1.1.15" %}

package:
  name: secapr
  version: {{ version }}

source:
  url: https://github.com/AntonelliLab/seqcap_processor/archive/v{{ version }}.tar.gz
  sha256: 0bf985591b8c44f69ca1d4c40d0d37c871d914336d1846a70cad209fcab529c1

build:
  skip: True  # [not py27] 
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - secapr = secapr.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - pandas
    - matplotlib
    - biopython
    - trimmomatic
    - fastqc
    - abyss
    - spades
    - blast
    - mafft
    - muscle
    - emboss
    - bwa
    - samtools

test:
  imports:
    - secapr
  commands:
    - secapr --version

about:
  home: 'https://github.com/AntonelliLab/seqcap_processor'
  license: MIT
  license_file: LICENSE
  summary: 'Process sequence-capture FASTQ files into alignments for phylogenetic analyses. Integrates allele phasing, producing haplotype alignments.'
